--- #YAML:1.0
name:                CORBA-JAVA
version:             2.66
abstract:            IDL compiler to JAVA (idlj clone)
license:             ~
author:              
    - Francois PERRAD (francois.perrad@gadz.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CORBA::IDL:                    2.61
    CORBA::XMLSchemas:             2.6
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
