# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CORBA-JAVA
version:      2.50
version_from: lib/CORBA/JAVA.pm
installdirs:  site
requires:
    CORBA::IDL:                    2.47
    CORBA::XMLSchemas:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
