# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CORBA-JAVA
version:      2.49
version_from: class.pm
installdirs:  site
requires:
    CORBA::IDL::node:              2.44
    CORBA::XMLSchemas::xsd:        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
